import producto1 from '../assets/banner1.jpeg';
import producto2 from '../assets/banner2.jpeg';
import producto3 from '../assets/banner3.jpeg';
import producto4 from '../assets/banner4.jpeg';
import producto5 from '../assets/banner5.jpeg';
import producto6 from '../assets/banner6.jpeg';
import producto7 from '../assets/banner7.jpeg';
import producto8 from '../assets/banner8.jpeg';
import producto9 from '../assets/banner9.jpeg';
import producto10 from '../assets/banner10.jpeg';
import producto11 from '../assets/banner11.jpeg';
import producto12 from '../assets/banner12.jpeg';
import producto13 from '../assets/banner13.jpeg';
import producto14 from '../assets/banner14.jpeg';
import producto15 from '../assets/banner15.jpeg';
import producto16 from '../assets/banner16.jpg';
import producto17 from '../assets/banner17.jpeg';
import producto18 from '../assets/banner18.jpeg';
import producto19 from '../assets/banner19.jpeg';
import producto20 from '../assets/banner20.jpeg';
import producto21 from '../assets/banner21.jpeg';
import producto22 from '../assets/banner22.jpeg';
import producto25 from '../assets/banner25.jpeg';
import producto26 from '../assets/banner26.jpeg';
import producto27 from '../assets/banner27.jpeg';
import producto28 from '../assets/banner28.jpeg';
import producto29 from '../assets/banner29.jpeg';
import producto30 from '../assets/banner30.jpeg';
import producto31 from '../assets/banner31.jpeg';
import producto32 from '../assets/banner32.jpeg';
import producto33 from '../assets/banner33.jpeg';
import producto34 from '../assets/banner34.jpeg';
import producto35 from '../assets/banner35.jpeg';
import producto36 from '../assets/banner36.jpeg';
import producto37 from '../assets/banner37.jpeg';
import producto38 from '../assets/banner38.jpeg';
import producto39 from '../assets/banner39.jpeg';
import producto40 from '../assets/banner40.jpeg';
import producto41 from '../assets/banner41.jpeg';
import producto42 from '../assets/banner42.jpeg';
import producto43 from '../assets/banner43.jpeg';
import producto44 from '../assets/banner44.jpeg';
import producto45 from '../assets/banner45.jpeg';
import producto46 from '../assets/banner46.jpeg';
import producto47 from '../assets/banner47.jpeg';
import producto48 from '../assets/banner48.jpeg';
import producto49 from '../assets/banner49.jpeg';
import producto50 from '../assets/banner50.jpeg';
import producto51 from '../assets/banner51.jpeg';
import producto52 from '../assets/banner52.jpeg';
import producto53 from '../assets/banner53.jpeg';
import producto54 from '../assets/banner54.jpeg';
import producto55 from '../assets/banner55.jpeg';
import producto56 from '../assets/banner56.jpeg';
import producto57 from '../assets/banner57.jpeg';
import producto58 from '../assets/banner58.jpeg';
import producto59 from '../assets/banner59.jpeg';
import producto60 from '../assets/banner60.jpeg';
import producto61 from '../assets/banner61.jpeg';
import producto62 from '../assets/banner61.jpeg';
import producto63 from '../assets/banner63.jpeg';
import producto64 from '../assets/banner64.jpeg';
import producto65 from '../assets/banner65.jpeg';
import producto66 from '../assets/banner66.jpeg';
import producto67 from '../assets/banner67.jpeg';
import producto68 from '../assets/banner68.jpeg';
import producto69 from '../assets/banner69.jpeg';
import producto70 from '../assets/banner70.jpeg';
import producto71 from '../assets/banner71.jpeg';
import producto72 from '../assets/banner72.jpeg';
import fondo from '../assets/banner5.jpeg';

export const productos = [
    { id: 1, nombre: 'Escritorio gamer max blue',                           descripcion: 'El Escritorio Gamer Max Blue es la elección ideal para los entusiastas de los videojuegos que buscan un ambiente cómodo y estilizado. Su diseño contemporáneo y audaz, con un acabado azul vibrante, aporta un toque moderno a cualquier espacio. Este escritorio está diseñado para soportar múltiples monitores y equipos, con una superficie amplia que permite disfrutar de largas sesiones de juego sin incomodidades. Además, cuenta con soluciones integradas para la gestión de cables, manteniendo un aspecto ordenado y limpio. Fabricado con materiales duraderos, el Escritorio Gamer Max Blue no solo es funcional, sino que también asegura una resistencia óptima, convirtiéndolo en el compañero perfecto para gamers exigentes.', img: producto1, categoria: 'zona gamer', precio:'$380.000' },
    { id: 2, nombre: 'Escritorio en L Axis modular',                        descripcion: 'El Escritorio en L Axis modular es una solución perfecta para quienes necesitan un espacio de trabajo versátil y eficiente. Su diseño en forma de L maximiza el área disponible, permitiendo organizar cómodamente múltiples dispositivos, como computadoras, monitores y accesorios, sin comprometer la estética. La modularidad de este escritorio permite adaptarlo a diferentes configuraciones y espacios, ofreciendo la flexibilidad que muchos profesionales y gamers requieren. Fabricado con materiales de alta calidad, el escritorio Axis asegura estabilidad y resistencia, mientras que su acabado elegante complementa cualquier entorno, ya sea en casa o en la oficina. Ideal para quienes buscan funcionalidad y estilo en su área de trabajo.', img: producto2, categoria: 'estudio', precio:'$320.000' },
    { id: 3, nombre: 'Escritorio gamer Domo modular',                       descripcion: 'El Escritorio Gamer Domo modular está diseñado para ofrecer una experiencia de juego envolvente y cómoda. Su estructura modular permite ajustar el diseño según tus necesidades y preferencias, brindando un espacio personalizado para tu configuración de juego. Con un acabado moderno y elegante, este escritorio cuenta con un amplio espacio para monitores, teclado y otros dispositivos, manteniendo todo organizado y al alcance de la mano. Además, su diseño ergonómico promueve una postura saludable durante largas sesiones de juego, mientras que los materiales de alta calidad garantizan durabilidad y resistencia. Ideal para gamers que buscan funcionalidad sin sacrificar estilo.', img: producto3, categoria: 'zona gamer', precio:'$300.000' },
    { id: 4, nombre: 'Mesa de television Urban modular',                    descripcion: 'La Mesa de Televisión Urban modular es una pieza versátil y contemporánea que se adapta perfectamente a cualquier sala de estar. Su diseño modular permite personalizar la disposición de los elementos, brindando flexibilidad en la organización del espacio. Fabricada con materiales de alta calidad, esta mesa no solo ofrece una superficie robusta para tu televisor, sino también amplios compartimentos de almacenamiento para equipos de entretenimiento y accesorios. Con acabados elegantes y un estilo minimalista, la Mesa Urban se integra armoniosamente en diferentes estilos decorativos, convirtiéndose en un punto focal atractivo y funcional en tu hogar.', img: producto4, categoria: 'sala' },
    { id: 5, nombre: 'Escritorio gamer Basic modular',                      descripcion: 'El Escritorio Gamer Basic modular es la elección perfecta para aquellos que buscan un espacio de trabajo y juego funcional. Su diseño modular permite adaptarlo a diferentes configuraciones, optimizando el uso del espacio en tu habitación o oficina. Fabricado con materiales duraderos y resistentes, este escritorio ofrece una superficie amplia para colocar monitores, teclados y otros accesorios de juego. Su estética moderna se complementa con detalles que añaden un toque de estilo, mientras que la gestión de cables integrada ayuda a mantener tu área de trabajo ordenada. Ideal para gamers y profesionales por igual, garantiza comodidad y eficiencia en cada sesión.', img: producto5, categoria: 'zona gamer' },
    { id: 6, nombre: 'Mesa de Television Town modular',                     descripcion: 'La Mesa de Televisión Town modular combina funcionalidad y estilo moderno. Diseñada para adaptarse a diferentes espacios, su estructura modular permite configuraciones personalizables, haciendo que sea ideal para cualquier sala de estar. Fabricada con materiales de alta calidad, esta mesa ofrece un acabado elegante y resistente. Su diseño incluye estantes abiertos y cerrados, proporcionando un amplio espacio de almacenamiento para dispositivos multimedia, libros y decoraciones. Además, su aspecto minimalista se integra perfectamente con cualquier decoración, convirtiéndola en un elemento central en tu hogar.', img: producto6, categoria: 'sala' },
    { id: 7, nombre: 'Escritorio gamer Trinity modular',                    descripcion: 'El Escritorio Gamer Trinity modular está diseñado para ofrecer una experiencia de juego inmersiva. Su estructura robusta y ajustable permite adaptarse a diferentes configuraciones, brindando comodidad y estilo. Con una superficie amplia, es perfecto para múltiples monitores y accesorios, mientras que su diseño moderno y elegante se integra perfectamente en cualquier entorno de juego. Además, cuenta con espacio de almacenamiento inteligente para mantener todo organizado y al alcance. Es la opción ideal para los gamers que buscan rendimiento y estética en su estación de trabajo.', img: producto7, categoria: 'zona gamer' },
    { id: 8, nombre: 'Centro de Entretenimiento Roni modular',              descripcion: 'El Centro de Entretenimiento Roni combina estilo y funcionalidad en un diseño fijo que optimiza el espacio. Ideal para crear una zona multimedia, cuenta con compartimentos para almacenamiento y espacio para colocar dispositivos electrónicos. Su acabado moderno añade un toque sofisticado al salón, adaptándose bien a decoraciones contemporáneas.', img: producto8, categoria: 'sala' },
    { id: 9, nombre: 'Escritorio basic Batistine modular',                  descripcion: 'El escritorio Basic Batistine modular combina simplicidad y funcionalidad en un diseño adaptable. Su estructura modular permite configurarlo de diferentes maneras para ajustarse a diversas necesidades de espacio y organización. Con líneas limpias y un acabado minimalista, es perfecto tanto para el hogar como para una oficina. Su diseño versátil permite añadir módulos adicionales, optimizando el espacio de trabajo y proporcionando una superficie amplia y cómoda para todas tus actividades diarias.', img: producto9, categoria: 'estudio' },
    { id: 10, nombre: 'Escritorio gamer Lax blue',                          descripcion: 'El escritorio gamer Lax blue ofrece una experiencia de juego cómoda y moderna, destacándose con detalles en azul vibrante. Su diseño espacioso permite acomodar fácilmente múltiples monitores, teclado y otros accesorios. La estructura es robusta y está pensada para brindar estabilidad, ideal para largas sesiones de juego. Su estilo y funcionalidad hacen de este escritorio una excelente elección para cualquier gamer.', img: producto10, categoria: 'zona gamer' },
    { id: 11, nombre: 'Escritorio gamer Lax red',                           descripcion: 'El escritorio gamer Lax red es ideal para jugadores que buscan un diseño ergonómico y llamativo. Su estructura sólida y superficie espaciosa permiten organizar múltiples pantallas y accesorios de juego sin sacrificar comodidad. Los detalles en color rojo agregan un estilo vibrante, mientras que su construcción asegura estabilidad incluso en sesiones intensas.', img: producto11, categoria: 'zona gamer' },
    { id: 12, nombre: 'Escritorio gamer max red',                           descripcion: 'El Escritorio Gamer Max Red es ideal para los amantes de los videojuegos que buscan un espacio de juego atractivo y funcional. Con un diseño moderno y detalles en color rojo, ofrece un estilo audaz y dinámico. Su estructura robusta proporciona estabilidad, mientras que la superficie amplia permite acomodar múltiples monitores, teclado y otros accesorios. Equipado con soportes y espacios adicionales para dispositivos, el Escritorio Gamer Max Red asegura una experiencia organizada y cómoda, adaptada a largas sesiones de juego.', img: producto12, categoria: 'zona gamer' },
    { id: 13, nombre: 'Mesa tv Good 50"',                                   descripcion: 'La Mesa TV Good de 50 pulgadas es una pieza compacta y funcional, perfecta para espacios más reducidos. Con un diseño sencillo y contemporáneo, esta mesa combina una estructura estable con acabados en tonos neutros que aportan elegancia sin sobrecargar el ambiente. Incluye compartimentos abiertos para dispositivos electrónicos y estantes cerrados para guardar otros objetos. Su tamaño optimizado y su estilo versátil la convierten en una opción ideal para quienes buscan una solución práctica y con estilo en el área de entretenimiento.', img: producto13, categoria: 'sala' },
    { id: 14, nombre: 'Mesa tv Mikasa 65"',                                 descripcion: 'La mesa TV Mikasa de 65 pulgadas destaca por su diseño contemporáneo y elegante. Con acabados en tonos madera y detalles en metal, esta mesa combina estilo y resistencia. Cuenta con múltiples compartimentos abiertos y cerrados, ideales para almacenar consolas, controles y otros accesorios. Su estructura robusta asegura estabilidad, mientras que su estilo moderno se integra perfectamente en cualquier ambiente, ofreciendo una solución práctica y estética para organizar el espacio audiovisual del hogar.', img: producto14, categoria: 'sala' },
    { id: 15, nombre: 'Mesa tv Flat 65"',                                   descripcion: 'Esta mesa para TV de hasta 65 pulgadas combina diseño moderno y funcionalidad. Fabricada con materiales resistentes, ofrece un amplio espacio de almacenamiento en compartimentos abiertos y cerrados, ideal para dispositivos multimedia y accesorios decorativos. Su acabado minimalista y líneas limpias se adaptan a diversos estilos de decoración, aportando elegancia y organización a cualquier sala de estar.', img: producto15, categoria: 'sala' },
    { id: 16, nombre: 'Mesa tv Tunez modular',                              descripcion: 'La Mesa TV Túnez Modular es una pieza elegante y versátil que combina funcionalidad y estilo en cualquier sala de estar. Con un diseño modular, permite adaptar su configuración según tus necesidades y el espacio disponible. Su acabado moderno y sobrio la convierte en un complemento ideal para cualquier decoración, mientras que los compartimentos de almacenamiento ofrecen suficiente espacio para dispositivos multimedia, controles remotos y otros accesorios. Además, su superficie robusta es perfecta para soportar televisores de diferentes tamaños, asegurando estabilidad y resistencia. La Mesa TV Túnez Modular no solo optimiza tu espacio, sino que también añade un toque contemporáneo a tu hogar.', img: producto16, categoria: 'sala' },
    { id: 17, nombre: 'Mesa tv y sonido Prato Rovere 32"',                  descripcion: 'La Mesa TV y Sonido Prato Rovere 32" es la opción ideal para quienes buscan combinar estilo y funcionalidad en un solo mueble. Su diseño elegante en un acabado de roble aporta un aire cálido y moderno, perfecto para cualquier sala de estar. Esta mesa cuenta con un espacio optimizado para acomodar televisores de hasta 32 pulgadas y está equipada con estantes adicionales para dispositivos de audio y video, como reproductores de DVD y consolas de videojuegos. Los detalles de su construcción garantizan una gran durabilidad, mientras que su diseño compacto la hace adecuada incluso para espacios más reducidos. La Mesa TV y Sonido Prato Rovere es perfecta para disfrutar de tus programas y películas favoritas en un ambiente acogedor y bien organizado.', img: producto17, categoria: 'sala' },
    { id: 18, nombre: 'Mesa tv y sonido Prato wengue 32"',                  descripcion: 'La Mesa TV y Sonido Prato Wengué 32" es una pieza contemporánea que destaca por su elegancia y funcionalidad. Con un acabado en wengué oscuro, aporta un toque sofisticado a cualquier ambiente, convirtiéndose en el centro de atención de tu sala de estar. Diseñada para soportar televisores de hasta 32 pulgadas, esta mesa incluye estantes adicionales para almacenar dispositivos de entretenimiento como reproductores de DVD, consolas de videojuegos y otros accesorios, manteniéndolos organizados y al alcance. Su estructura robusta y duradera asegura una larga vida útil, mientras que su diseño estilizado se adapta perfectamente a espacios modernos y minimalistas. La Mesa TV y Sonido Prato Wengué es la elección ideal para quienes buscan una combinación de estilo y practicidad en su mueble para televisión.', img: producto18, categoria: 'sala' },
    { id: 19, nombre: 'Mesa centro Urban',                                  descripcion: 'La Mesa Centro Urban es una pieza de mobiliario que fusiona modernidad y funcionalidad en un diseño elegante. Ideal para salas de estar contemporáneas, su superficie amplia proporciona un espacio perfecto para colocar revistas, tazas o decoraciones, mientras que su estructura robusta garantiza estabilidad y durabilidad. Con un acabado en tonos neutros y líneas limpias, esta mesa se adapta a una variedad de estilos decorativos, desde minimalista hasta industrial. Además, su diseño funcional permite utilizarla como punto de encuentro en reuniones familiares o con amigos, creando un ambiente acogedor y chic en tu hogar. La Mesa Centro Urban es, sin duda, una adición práctica y estética para cualquier sala.', img: producto19, categoria: 'habitación' },
    { id: 20, nombre: 'Closet Burdeos modular',                             descripcion: 'El closet Burdeos Modular es la solución ideal para quienes buscan un equilibrio entre estilo y funcionalidad en el almacenamiento. Su diseño modular permite adaptarse a diferentes espacios, ofreciendo versatilidad y personalización en la distribución. Fabricado con materiales de alta calidad, este armario no solo proporciona un amplio espacio para ropa y accesorios, sino que también presenta un acabado en un elegante tono burdeos que añade un toque sofisticado a cualquier habitación. Las puertas cuentan con un sistema de apertura suave, y el interior está diseñado para maximizar el espacio, incluyendo estantes ajustables y barras para colgar. Ya sea en un dormitorio, vestidor o área de servicio, el Armario Burdeos Modular se convierte en un elemento esencial que combina estética y practicidad.', img: producto20, categoria: 'habitación' },
    { id: 21, nombre: 'Closet Bilbao modular',                              descripcion: 'El Closet Bilbao Modular es una opción perfecta para quienes buscan maximizar el espacio de almacenamiento sin sacrificar el estilo. Con un diseño modular y elegante, este closet se adapta a diversas configuraciones y tamaños de habitación, lo que permite personalizar su disposición según las necesidades individuales. Fabricado con materiales duraderos, su acabado suave y moderno aporta un toque contemporáneo a cualquier decoración. El interior cuenta con estantes ajustables y barras para colgar, proporcionando un amplio espacio para ropa, zapatos y accesorios. Su funcionalidad se complementa con puertas de apertura suave, lo que facilita el acceso a todo lo que necesitas. Ideal para dormitorios y vestidores, el Closet Bilbao Modular combina calidad y diseño para optimizar el almacenamiento en tu hogar.', img: producto21, categoria: 'habitación' },
    { id: 22, nombre: 'Closet Vito caramelo modular',                       descripcion: 'El Closet Vito Modular es la solución ideal para quienes desean un sistema de almacenamiento versátil y elegante. Este closet modular está diseñado para adaptarse a diferentes espacios y estilos, permitiendo configuraciones personalizadas según tus necesidades. Con un acabado contemporáneo y una construcción robusta, el Closet Vito no solo ofrece una apariencia moderna, sino también durabilidad a largo plazo.', img: producto22, categoria: 'habitación' },
    { id: 25, nombre: 'Closet Vito rovere modular',                         descripcion: 'El Closet Vito Modular es la solución ideal para quienes desean un sistema de almacenamiento versátil y elegante. Este closet modular está diseñado para adaptarse a diferentes espacios y estilos, permitiendo configuraciones personalizadas según tus necesidades. Con un acabado contemporáneo y una construcción robusta, el Closet Vito no solo ofrece una apariencia moderna, sino también durabilidad a largo plazo', img: producto25, categoria: 'habitación' },
    { id: 26, nombre: 'Cama Moscow doble modular',                          descripcion: 'La Cama Moscow Doble Modular es la elección perfecta para quienes buscan comodidad y funcionalidad en su dormitorio. Su diseño modular permite una fácil adaptación a diferentes espacios, lo que la convierte en una opción ideal para habitaciones grandes o pequeñas. Fabricada con materiales de alta calidad, la cama ofrece una base robusta y duradera que asegura un soporte óptimo para un descanso reparador.', img: producto26, categoria: 'habitación' },
    { id: 27, nombre: 'Closet Belén modular',                               descripcion: 'El Closet Belén Modular es la solución ideal para quienes buscan organización y estilo en su espacio. Con un diseño modular, este closet se adapta fácilmente a las dimensiones y necesidades de cualquier habitación, permitiendo personalizar su configuración para optimizar el almacenamiento.', img: producto27, categoria: 'habitación' },
    { id: 28, nombre: 'Closet Star modular',                                descripcion: 'Este closet modular combina diseño moderno y funcionalidad en una estructura adaptable a cualquier tipo de espacio. Con múltiples compartimentos ajustables, es perfecto para organizar ropa, zapatos y accesorios de manera eficiente y personalizada. Su versatilidad permite adaptarlo a diferentes necesidades y estilos, ideal para quienes buscan maximizar el espacio sin sacrificar estilo. Fabricado con materiales de alta calidad, el Closet Star modular ofrece durabilidad y resistencia, asegurando una inversión a largo plazo. Su fácil montaje permite que se ajuste a habitaciones de diversos tamaños, siendo una excelente solución para el almacenamiento en hogares contemporáneos.', img: producto28, categoria: 'habitación' },
    { id: 29, nombre: 'Closet Nova modular',                                descripcion: 'Este moderno closet modular está diseñado para quienes buscan flexibilidad y estilo en el almacenamiento. Con estantes y cajones ajustables, el Closet Nova permite organizar ropa, calzado y accesorios de manera personalizada y ordenada. Su diseño optimiza el espacio vertical, ideal para habitaciones pequeñas o grandes, adaptándose sin esfuerzo a tus necesidades. Fabricado con materiales resistentes y acabados elegantes, el Closet Nova combina funcionalidad y estética en un solo mueble. Además, su fácil ensamblaje permite reconfigurarlo cuando sea necesario, convirtiéndolo en una opción práctica y duradera para hogares en constante evolución.', img: producto29, categoria: 'habitación' },
    { id: 30, nombre: 'Combo Cama Toscana modular',                         descripcion: ' La Cama Toscana modular destaca por su diseño elegante y funcionalidad adaptable, ideal para cualquier estilo de habitación. Esta cama no solo brinda comodidad, sino también opciones de almacenamiento integrado, permitiendo organizar ropa de cama, libros u otros objetos de forma discreta y accesible. Con un sistema modular, puedes ajustar su estructura según tus necesidades, convirtiéndola en una opción versátil para espacios pequeños o multifuncionales. Fabricada con materiales de alta calidad, ofrece resistencia y durabilidad. La Cama Toscana modular es la elección perfecta para quienes buscan optimizar el espacio sin renunciar a un estilo sofisticado y contemporáneo.', img: producto30, categoria: 'habitación' },
    { id: 31, nombre: 'Closet Romina Caramelo modular',                     descripcion: 'El Closet Romina modular es la solución ideal para quienes necesitan flexibilidad y organización en su espacio. Este closet ofrece múltiples compartimentos, repisas y cajones ajustables, permitiéndote personalizarlo según tus necesidades de almacenamiento. Su diseño optimiza cada rincón y facilita el acceso a la ropa y accesorios, brindando un orden impecable en cualquier dormitorio. Fabricado con materiales de alta durabilidad y acabados modernos, el Closet Romina aporta estilo y funcionalidad a tu hogar. Su montaje sencillo y estructura modular permiten reconfigurarlo fácilmente, adaptándose a cambios en el espacio o en tus preferencias de diseño.', img: producto31, categoria: 'habitación' },
    { id: 32, nombre: 'Closet Romina Rovere modular',                       descripcion: 'El Closet Romina modular es la solución ideal para quienes necesitan flexibilidad y organización en su espacio. Este closet ofrece múltiples compartimentos, repisas y cajones ajustables, permitiéndote personalizarlo según tus necesidades de almacenamiento. Su diseño optimiza cada rincón y facilita el acceso a la ropa y accesorios, brindando un orden impecable en cualquier dormitorio. Fabricado con materiales de alta durabilidad y acabados modernos, el Closet Romina aporta estilo y funcionalidad a tu hogar. Su montaje sencillo y estructura modular permiten reconfigurarlo fácilmente, adaptándose a cambios en el espacio o en tus preferencias de diseño.', img: producto32, categoria: 'habitación' },
    { id: 33, nombre: 'Closet Berlín Duna modular',                         descripcion: 'Con un diseño contemporáneo y una estructura flexible, el Closet Berlín modular es perfecto para maximizar el espacio de almacenamiento en cualquier habitación. Este closet cuenta con estantes ajustables, barras para colgar prendas y cajones amplios, permitiendo una organización detallada y accesible. Su sistema modular permite adaptarlo a distintos espacios, lo que lo hace ideal para habitaciones de tamaño variado. Fabricado con materiales de alta calidad, el Closet Berlín garantiza durabilidad y resistencia, añadiendo un toque moderno y funcional al ambiente. Su diseño elegante y práctico facilita mantener el orden de forma eficiente y personalizad', img: producto33, categoria: 'habitación' },
    { id: 34, nombre: 'Closet Berlín Caramelo modular',                     descripcion: 'Con un diseño contemporáneo y una estructura flexible, el Closet Berlín modular es perfecto para maximizar el espacio de almacenamiento en cualquier habitación. Este closet cuenta con estantes ajustables, barras para colgar prendas y cajones amplios, permitiendo una organización detallada y accesible. Su sistema modular permite adaptarlo a distintos espacios, lo que lo hace ideal para habitaciones de tamaño variado. Fabricado con materiales de alta calidad, el Closet Berlín garantiza durabilidad y resistencia, añadiendo un toque moderno y funcional al ambiente. Su diseño elegante y práctico facilita mantener el orden de forma eficiente y personalizad', img: producto34, categoria: 'habitación' },
    { id: 35, nombre: 'Closet Berlín Rovere modular',                       descripcion: 'Con un diseño contemporáneo y una estructura flexible, el Closet Berlín modular es perfecto para maximizar el espacio de almacenamiento en cualquier habitación. Este closet cuenta con estantes ajustables, barras para colgar prendas y cajones amplios, permitiendo una organización detallada y accesible. Su sistema modular permite adaptarlo a distintos espacios, lo que lo hace ideal para habitaciones de tamaño variado. Fabricado con materiales de alta calidad, el Closet Berlín garantiza durabilidad y resistencia, añadiendo un toque moderno y funcional al ambiente. Su diseño elegante y práctico facilita mantener el orden de forma eficiente y personalizad', img: producto35, categoria: 'habitación' },
    { id: 36, nombre: 'Cama Doble Alcalá Caramelo modular',                 descripcion: 'Diseñada para ofrecer comodidad y funcionalidad, la Cama Doble Alcalá modular es ideal para optimizar el espacio en cualquier dormitorio. Su estructura modular permite añadir componentes de almacenamiento integrados, como cajones y compartimentos ocultos, perfectos para guardar ropa de cama, libros o accesorios. Fabricada con materiales de alta resistencia y un diseño elegante, esta cama se adapta a distintos estilos de decoración, brindando un ambiente moderno y organizado. Su sistema modular permite modificar la disposición de los compartimentos según tus necesidades, siendo una opción práctica y versátil para aprovechar al máximo el espacio sin sacrificar comodidad.', img: producto36, categoria: 'habitación' },
    { id: 37, nombre: 'Cama Doble Alcalá Wengue modular',                   descripcion: 'Diseñada para ofrecer comodidad y funcionalidad, la Cama Doble Alcalá modular es ideal para optimizar el espacio en cualquier dormitorio. Su estructura modular permite añadir componentes de almacenamiento integrados, como cajones y compartimentos ocultos, perfectos para guardar ropa de cama, libros o accesorios. Fabricada con materiales de alta resistencia y un diseño elegante, esta cama se adapta a distintos estilos de decoración, brindando un ambiente moderno y organizado. Su sistema modular permite modificar la disposición de los compartimentos según tus necesidades, siendo una opción práctica y versátil para aprovechar al máximo el espacio sin sacrificar comodidad.', img: producto37, categoria: 'habitación' },
    { id: 38, nombre: 'Combo Cama Doble Praga Wengue modular',              descripcion: 'La Cama Doble Praga modular combina un diseño elegante con una gran funcionalidad para maximizar el uso del espacio en tu dormitorio. Esta cama cuenta con módulos de almacenamiento incorporados, ideales para guardar ropa de cama, libros u otros objetos personales de manera discreta y accesible. Su estructura versátil permite reorganizar los compartimentos según las necesidades, proporcionando una solución adaptable para espacios pequeños o multifuncionales. Fabricada con materiales duraderos y acabados modernos, la Cama Doble Praga ofrece tanto estilo como resistencia. Es la elección perfecta para quienes buscan un mobiliario práctico y sofisticado en el hogar.', img: producto38, categoria: 'habitación' },
    { id: 39, nombre: 'Combo Cama Doble Praga Caramelo modular',            descripcion: 'La Cama Doble Praga modular combina un diseño elegante con una gran funcionalidad para maximizar el uso del espacio en tu dormitorio. Esta cama cuenta con módulos de almacenamiento incorporados, ideales para guardar ropa de cama, libros u otros objetos personales de manera discreta y accesible. Su estructura versátil permite reorganizar los compartimentos según las necesidades, proporcionando una solución adaptable para espacios pequeños o multifuncionales. Fabricada con materiales duraderos y acabados modernos, la Cama Doble Praga ofrece tanto estilo como resistencia. Es la elección perfecta para quienes buscan un mobiliario práctico y sofisticado en el hogar.', img: producto39, categoria: 'habitación' },
    { id: 40, nombre: 'Cama Nido Lísboa modular',                           descripcion: 'La Cama Nido Lísboa modular es ideal para maximizar espacio y funcionalidad en el dormitorio. Este modelo incorpora una cama nido inferior que se despliega fácilmente, perfecta para habitaciones compartidas o para recibir visitas. Su diseño modular permite agregar compartimentos de almacenamiento, útiles para organizar ropa de cama, juguetes u otros accesorios. Fabricada con materiales de alta calidad, la Cama Nido Lísboa combina durabilidad y estilo, adaptándose a distintos estilos de decoración. Su estructura compacta es ideal para habitaciones pequeñas, ofreciendo una solución práctica y cómoda sin sacrificar elegancia.', img: producto40, categoria: 'habitación' },
    { id: 41, nombre: 'Closet Bari Caramelo modular',                       descripcion: 'El Closet Bari modular destaca por su diseño elegante y su capacidad de adaptarse a cualquier espacio. Con estantes ajustables, barras para colgar y cajones amplios, permite una organización personalizada para mantener la ropa y accesorios en perfecto orden. Su estructura modular es ideal para optimizar cada rincón, adaptándose a diferentes tamaños de habitación. Fabricado con materiales de alta resistencia y acabados modernos, el Closet Bari ofrece durabilidad y estilo, complementando cualquier decoración. Además, su fácil ensamblaje y flexibilidad lo convierten en una excelente opción para quienes buscan versatilidad y funcionalidad en un solo mueble.', img: producto41, categoria: 'habitación' },
    { id: 42, nombre: 'Closet Bari Duna modular',                           descripcion: 'El Closet Bari modular destaca por su diseño elegante y su capacidad de adaptarse a cualquier espacio. Con estantes ajustables, barras para colgar y cajones amplios, permite una organización personalizada para mantener la ropa y accesorios en perfecto orden. Su estructura modular es ideal para optimizar cada rincón, adaptándose a diferentes tamaños de habitación. Fabricado con materiales de alta resistencia y acabados modernos, el Closet Bari ofrece durabilidad y estilo, complementando cualquier decoración. Además, su fácil ensamblaje y flexibilidad lo convierten en una excelente opción para quienes buscan versatilidad y funcionalidad en un solo mueble.', img: producto42, categoria: 'habitación' },
    { id: 43, nombre: 'Closet Bari Rovere modular',                         descripcion: 'El Closet Bari modular destaca por su diseño elegante y su capacidad de adaptarse a cualquier espacio. Con estantes ajustables, barras para colgar y cajones amplios, permite una organización personalizada para mantener la ropa y accesorios en perfecto orden. Su estructura modular es ideal para optimizar cada rincón, adaptándose a diferentes tamaños de habitación. Fabricado con materiales de alta resistencia y acabados modernos, el Closet Bari ofrece durabilidad y estilo, complementando cualquier decoración. Además, su fácil ensamblaje y flexibilidad lo convierten en una excelente opción para quienes buscan versatilidad y funcionalidad en un solo mueble.', img: producto43, categoria: 'habitación' },
    { id: 44, nombre: 'Escritorio Space Extensible modular',                descripcion: 'El Escritorio Space Extensible modular es la solución perfecta para espacios de trabajo dinámicos y modernos. Su diseño ajustable permite expandir o reducir su tamaño según las necesidades, ideal para áreas pequeñas o espacios multifuncionales. Equipado con compartimentos y repisas, facilita la organización de documentos, herramientas de trabajo y dispositivos electrónicos, manteniendo el área de trabajo despejada y funcional. Fabricado con materiales de alta calidad, este escritorio garantiza durabilidad y estabilidad. Su estructura modular se adapta a diferentes configuraciones, brindando una experiencia de trabajo cómoda y personalizable, ideal para oficinas en casa o espacios de estudio.', img: producto44, categoria: 'estudio' },  
    { id: 45, nombre: 'Escritorio en L Tiny Blanco modular',                descripcion: 'Compacto y funcional, el Escritorio en L Tiny modular es perfecto para maximizar el espacio en áreas pequeñas sin sacrificar comodidad. Su diseño en forma de L permite aprovechar cada rincón, ofreciendo una amplia superficie para trabajar o estudiar. Incluye compartimentos integrados que facilitan la organización de documentos, dispositivos y accesorios, manteniendo el espacio ordenado y accesible. Su estructura modular permite personalizar la configuración según las necesidades, adaptándose tanto a esquinas como a espacios abiertos. Fabricado con materiales resistentes y acabados modernos, este escritorio combina estilo y practicidad, ideal para oficinas en casa o habitaciones con espacio reducido.', img: producto45, categoria: 'estudio' },
    { id: 46, nombre: 'Escritorio en L Tiny Wengue modular',                descripcion: 'Compacto y funcional, el Escritorio en L Tiny modular es perfecto para maximizar el espacio en áreas pequeñas sin sacrificar comodidad. Su diseño en forma de L permite aprovechar cada rincón, ofreciendo una amplia superficie para trabajar o estudiar. Incluye compartimentos integrados que facilitan la organización de documentos, dispositivos y accesorios, manteniendo el espacio ordenado y accesible. Su estructura modular permite personalizar la configuración según las necesidades, adaptándose tanto a esquinas como a espacios abiertos. Fabricado con materiales resistentes y acabados modernos, este escritorio combina estilo y practicidad, ideal para oficinas en casa o habitaciones con espacio reducido.', img: producto46, categoria: 'estudio' },
    { id: 47, nombre: 'Escritorio en L Asturias Caramelo',                  descripcion: 'Diseñado para brindar un espacio de trabajo amplio y organizado, el Escritorio en L Asturias es ideal para oficinas y espacios de estudio. Su formato en L permite aprovechar al máximo las esquinas, optimizando el uso del espacio y ofreciendo suficiente superficie para colocar equipos, documentos y herramientas de trabajo. Este escritorio cuenta con cajones y repisas adicionales para mantener el área despejada y bien organizada. Fabricado con materiales de alta calidad y acabados modernos, el Escritorio Asturias combina durabilidad y estilo, adaptándose perfectamente a cualquier ambiente profesional o doméstico.', img: producto47, categoria: 'estudio' },
    { id: 48, nombre: 'Escritorio en L Asturias Duna',                      descripcion: 'Diseñado para brindar un espacio de trabajo amplio y organizado, el Escritorio en L Asturias es ideal para oficinas y espacios de estudio. Su formato en L permite aprovechar al máximo las esquinas, optimizando el uso del espacio y ofreciendo suficiente superficie para colocar equipos, documentos y herramientas de trabajo. Este escritorio cuenta con cajones y repisas adicionales para mantener el área despejada y bien organizada. Fabricado con materiales de alta calidad y acabados modernos, el Escritorio Asturias combina durabilidad y estilo, adaptándose perfectamente a cualquier ambiente profesional o doméstico.', img: producto48, categoria: 'estudio' },
    { id: 49, nombre: 'Escritorio Configurable Spaqua modular',             descripcion: 'El Escritorio Configurable Spaqua modular ofrece una solución flexible y moderna para cualquier espacio de trabajo. Diseñado para adaptarse a tus necesidades, este escritorio permite reorganizar sus módulos y ajustar su disposición según el área y las funciones deseadas. Con estantes, compartimentos y una superficie amplia, facilita el almacenamiento de dispositivos, documentos y útiles de trabajo, manteniendo el espacio despejado y ordenado. Fabricado con materiales resistentes y acabados sofisticados, el Spaqua modular es duradero y elegante. Su diseño configurable lo convierte en la opción perfecta para oficinas en casa o entornos de trabajo versátiles que requieren adaptabilidad.', img: producto49, categoria: 'estudio' },
    { id: 50, nombre: 'Escritorio con Biblioteca Wex',                      descripcion: 'El Escritorio con Biblioteca Wex combina un área de trabajo funcional con una solución de almacenamiento integrada, ideal para quienes buscan organización y estilo. Este escritorio cuenta con una biblioteca lateral que permite tener libros, documentos y objetos decorativos siempre a mano, optimizando el espacio y manteniendo el área de trabajo despejada. Su diseño compacto pero espacioso es perfecto para oficinas en casa o estudios. Fabricado con materiales duraderos y acabados modernos, el Escritorio Wex no solo es práctico, sino también estéticamente atractivo, complementando cualquier ambiente profesional o de estudio con un toque contemporáneo.', img: producto50, categoria: 'estudio' },
    { id: 51, nombre: 'Biblioteca Modular Ragnar',                          descripcion: 'La Biblioteca Modular Ragnar es la solución ideal para quienes buscan almacenamiento flexible y un diseño moderno. Compuesta por módulos ajustables, permite configurar estantes y compartimentos de diferentes tamaños para adaptarse a libros, decoraciones y otros objetos. Su estructura modular facilita personalizar su disposición según el espacio disponible y las necesidades de organización, siendo perfecta para salas, oficinas o estudios. Fabricada con materiales de alta calidad y acabados elegantes, la Biblioteca Ragnar es resistente y funcional. Su diseño versátil la convierte en un mueble decorativo que aporta orden y estilo a cualquier ambiente.', img: producto51, categoria: 'estudio' },
    { id: 52, nombre: 'Escritorio Sencillo Duna modular',                   descripcion: 'El Escritorio Sencillo modular ofrece un diseño minimalista y funcional, ideal para espacios de trabajo compactos o habitaciones pequeñas. Su estructura modular permite ajustar la disposición y añadir módulos adicionales para almacenamiento, adaptándose a tus necesidades de organización. Con una superficie de trabajo limpia y resistente, este escritorio es perfecto para estudiar, trabajar o realizar actividades cotidianas. Fabricado con materiales de calidad y acabados modernos, el Escritorio Sencillo combina durabilidad y estilo en un diseño compacto. Es la elección ideal para quienes buscan practicidad y estética en un mueble de bajo per', img: producto52, categoria: 'estudio' },
    { id: 53, nombre: 'Escritorio Sencillo Caramelo modular',               descripcion: 'El Escritorio Sencillo modular ofrece un diseño minimalista y funcional, ideal para espacios de trabajo compactos o habitaciones pequeñas. Su estructura modular permite ajustar la disposición y añadir módulos adicionales para almacenamiento, adaptándose a tus necesidades de organización. Con una superficie de trabajo limpia y resistente, este escritorio es perfecto para estudiar, trabajar o realizar actividades cotidianas. Fabricado con materiales de calidad y acabados modernos, el Escritorio Sencillo combina durabilidad y estilo en un diseño compacto. Es la elección ideal para quienes buscan practicidad y estética en un mueble de bajo per', img: producto53, categoria: 'estudio' },
    { id: 54, nombre: 'Estación de Trabajo Quadratta modular',              descripcion: 'La Estación de Trabajo Quadratta modular es la solución perfecta para un ambiente de trabajo altamente funcional y organizado. Su diseño modular permite configurar y ajustar el espacio a tus necesidades, integrando superficies amplias, estantes y compartimentos para almacenamiento de documentos, dispositivos y accesorios. Ideal para oficinas profesionales o espacios de trabajo en casa, esta estación de trabajo optimiza cada rincón y mantiene todo al alcance. Fabricada con materiales de alta calidad y acabados contemporáneos, la Quadratta es robusta y elegante, proporcionando un ambiente de trabajo cómodo, eficiente y estéticamente atractivo', img: producto54, categoria: 'estudio' },
    { id: 55, nombre: 'Combo Escritorio + Biblioteca Ragnar modular',       descripcion: 'Este combo combina funcionalidad y diseño moderno, ideal para espacios de trabajo completos y bien organizados. El escritorio ofrece una superficie amplia y cómoda para tareas diarias, mientras que la biblioteca modular Ragnar permite un almacenamiento flexible con estantes ajustables para libros, documentos y decoraciones. Gracias a su diseño modular, puedes configurar ambos elementos según el espacio disponible, adaptándolos fácilmente a tus necesidades. Fabricado con materiales duraderos y acabados elegantes, este combo aporta estilo y orden a cualquier oficina o estudio. Es la elección ideal para quienes buscan optimizar su espacio de trabajo con versatilidad y estética', img: producto55, categoria: 'estudio' },
    { id: 56, nombre: 'Escritorio en L Kyoto modular',                      descripcion: 'El Escritorio en L Kyoto modular es una opción elegante y funcional para maximizar el espacio de trabajo en cualquier habitación. Su diseño en forma de L permite aprovechar las esquinas, proporcionando una amplia superficie para computadoras, documentos y otros elementos esenciales. Este escritorio cuenta con estantes y cajones integrados, lo que facilita la organización de tus materiales y mantiene el área de trabajo ordenada. Fabricado con materiales de alta calidad y acabados modernos, el Kyoto no solo es resistente, sino que también agrega un toque contemporáneo a tu oficina o estudio. Su estructura modular permite adaptarlo fácilmente a diferentes configuraciones, haciendo que sea perfecto para cualquier entorno.', img: producto56, categoria: 'estudio' },
    { id: 57, nombre: 'Escritorio Repisas Lannister modular',               descripcion: 'El Escritorio Repisas Lannister modular combina un diseño contemporáneo con una funcionalidad excepcional, ideal para aquellos que buscan un espacio de trabajo organizado y estilizado. Este escritorio incluye repisas integradas que ofrecen un almacenamiento eficiente para libros, documentos y objetos decorativos, manteniendo el área de trabajo despejada y accesible. Su estructura modular permite personalizar la disposición de las repisas según las necesidades individuales, adaptándose a diferentes espacios y estilos. Fabricado con materiales de alta calidad, el Lannister es duradero y atractivo, convirtiéndolo en una opción perfecta para oficinas en casa o estudios que requieren tanto estilo como practicidad.', img: producto57, categoria: 'estudio' },
    { id: 58, nombre: 'Escritorio Biblioteca Trix modular',                 descripcion: 'El Escritorio Biblioteca Trix es la solución perfecta para quienes buscan combinar un área de trabajo eficiente con almacenamiento práctico. Su diseño innovador integra un escritorio espacioso con estantes y compartimentos que permiten organizar libros, documentos y objetos decorativos de manera accesible y estilizada. Ideal para oficinas en casa, estudios o habitaciones compartidas, este mueble maximiza el uso del espacio y mantiene todo al alcance de la mano. Fabricado con materiales de alta calidad y acabados modernos, el Trix no solo es funcional, sino que también aporta un toque contemporáneo a cualquier ambiente, convirtiéndolo en una elección práctica y atractiva.', img: producto58, categoria: 'estudio' },
    { id: 59, nombre: 'Escritorio en L Aisha Caramelo modular',             descripcion: 'El Escritorio en L Aisha modular es una opción elegante y versátil diseñada para optimizar el espacio de trabajo en cualquier entorno. Su estructura en forma de L permite maximizar las esquinas, proporcionando una amplia superficie para trabajar y almacenar materiales. Este escritorio cuenta con compartimentos integrados y estantes ajustables, lo que facilita la organización de documentos, dispositivos y accesorios, manteniendo todo al alcance y en orden. Fabricado con materiales de alta calidad y acabados modernos, el Aisha no solo es duradero, sino que también añade un toque contemporáneo a tu oficina o estudio. Su diseño modular se adapta fácilmente a diferentes configuraciones, convirtiéndolo en una solución práctica y estilizada para espacios de trabajo dinámicos', img: producto59, categoria: 'estudio' },
    { id: 60, nombre: 'Biblioteca Configurable Amatista modular',           descripcion: 'La Biblioteca Configurable Amatista modular es una opción excepcional para quienes buscan un sistema de almacenamiento flexible y atractivo. Su diseño modular permite personalizar la disposición de los estantes y compartimentos, adaptándose a tus necesidades y al espacio disponible. Ideal para libros, decoraciones y objetos personales, esta biblioteca maximiza el uso del espacio y aporta un estilo contemporáneo a cualquier habitación. Fabricada con materiales de alta calidad y acabados elegantes, la Amatista combina durabilidad y funcionalidad, convirtiéndose en un mueble versátil para oficinas, salas de estar o estudios. Su capacidad de configuración permite cambiar su forma y función a medida que tus necesidades evolucionan, garantizando un ambiente organizado y estilizado en todo momento.', img: producto60, categoria: 'estudio' },
    { id: 61, nombre: 'Combo Escritorio + Biblioteca Basic modular',        descripcion: 'Este combo funcional combina un escritorio espacioso con una biblioteca integrada, ofreciendo una solución completa para optimizar tu espacio de trabajo y almacenamiento. El escritorio cuenta con una superficie amplia y cómoda, perfecta para tareas diarias, mientras que la biblioteca ofrece estantes ajustables que permiten organizar libros, documentos y objetos decorativos de manera ordenada. Fabricado con materiales de alta calidad, el Combo Basic es duradero y se adapta a diferentes estilos de decoración. Su diseño modular permite configuraciones personalizables, haciendo de este combo una opción ideal para oficinas en casa, estudios o cualquier espacio que requiera funcionalidad y estilo sin complicaciones', img: producto61, categoria: 'estudio' },
    { id: 62, nombre: 'Escritorio Urban modular',                           descripcion: 'El Escritorio Urban modular es la combinación perfecta de estilo contemporáneo y funcionalidad, ideal para cualquier espacio de trabajo moderno. Su diseño minimalista ofrece una superficie amplia que facilita el trabajo diario, mientras que su estructura modular permite personalizar la configuración según las necesidades y el espacio disponible. Equipado con estantes y compartimentos, este escritorio promueve la organización, manteniendo tus documentos y materiales al alcance sin desordenar el área. Fabricado con materiales de alta calidad y acabados elegantes, el Urban es duradero y resistente, aportando un toque urbano y sofisticado a tu oficina o estudio. Es la elección ideal para quienes buscan un mueble práctico y estéticamente atractivo.', img: producto62, categoria: 'estudio' },
    { id: 63, nombre: 'Escritorio L Mikasa modular',                        descripcion: 'El Escritorio L Mikasa modular es una opción diseñada para maximizar el espacio y la funcionalidad en cualquier entorno de trabajo. Su diseño en forma de L permite aprovechar las esquinas de manera eficiente, proporcionando una amplia superficie para trabajar, estudiar o realizar diversas tareas. Equipado con estantes y cajones integrados, este escritorio facilita la organización de documentos, dispositivos y útiles, manteniendo el área de trabajo limpia y ordenada. Fabricado con materiales de alta calidad y acabados modernos, el Mikasa es tanto resistente como estilizado, adaptándose a diferentes estilos de decoración. Su estructura modular permite configuraciones personalizables, convirtiéndolo en una solución práctica y versátil para oficinas en casa o espacios de estudio.', img: producto63, categoria: 'estudio' },
    { id: 64, nombre: 'Combo Escritorio + Biblioteca Zeta modular',         descripcion: 'Este combo innovador combina un escritorio funcional con una biblioteca integrada, ofreciendo una solución ideal para maximizar el espacio y mantener la organización. El escritorio proporciona una superficie amplia y cómoda para trabajar, mientras que la biblioteca Zeta cuenta con estantes ajustables que permiten almacenar libros, documentos y objetos decorativos de manera ordenada y accesible. Fabricado con materiales de alta calidad, este combo es tanto duradero como estéticamente atractivo, con un diseño contemporáneo que se adapta a cualquier estilo de decoración. Su configuración modular permite personalizar la disposición según tus necesidades, haciendo de este combo una elección perfecta para oficinas en casa, estudios o habitaciones multifuncionales.', img: producto64, categoria: 'estudio' },
    { id: 65, nombre: 'Escritorio Kazan modular',                           descripcion: 'El Escritorio Kazan modular es una opción elegante y versátil, perfecta para optimizar espacios de trabajo en cualquier entorno. Su diseño contemporáneo ofrece una amplia superficie de trabajo, ideal para computadoras, documentos y otras herramientas esenciales. Este escritorio cuenta con módulos adicionales que permiten integrar estantes y compartimentos de almacenamiento, facilitando la organización y el acceso a tus materiales. Fabricado con materiales de alta calidad, el Kazan combina durabilidad y estilo, añadiendo un toque moderno a tu oficina o estudio. Su estructura modular se adapta fácilmente a diferentes configuraciones, lo que lo convierte en una solución práctica y funcional para quienes buscan un ambiente de trabajo cómodo y estéticamente atractiv', img: producto65, categoria: 'estudio' },
    { id: 66, nombre: 'Biblioteca Escalera París modular',                  descripcion: 'La Biblioteca Escalera París modular es una solución única y contemporánea para el almacenamiento y la exhibición de libros y decoraciones. Su diseño escalonado no solo maximiza el uso del espacio vertical, sino que también agrega un elemento visual atractivo a cualquier habitación. Con estantes ajustables y una estructura robusta, esta biblioteca permite organizar de manera eficiente libros, fotografías y objetos decorativos, manteniéndolos al alcance y en orden. Fabricada con materiales de alta calidad, la Biblioteca París combina durabilidad y estilo, convirtiéndola en una opción ideal para salas de estar, oficinas o estudios. Su versatilidad modular permite adaptarse a diferentes configuraciones y espacios, haciendo que sea una pieza funcional y estéticamente agradable en cualquier hogar.', img: producto66, categoria: 'estudio' },
    { id: 67, nombre: 'Escritorio Shelf Basic modular',                     descripcion: 'El Escritorio Shelf Basic modular es la opción ideal para quienes buscan un espacio de trabajo funcional y ordenado sin complicaciones. Su diseño sencillo y minimalista incluye estantes integrados que permiten almacenar libros, documentos y otros útiles de oficina, facilitando el acceso a todo lo necesario mientras se mantiene el área despejada. La amplia superficie de trabajo proporciona comodidad para realizar tareas diarias, ya sea en casa o en la oficina. Fabricado con materiales de alta calidad, el Shelf Basic es resistente y duradero, ofreciendo una combinación perfecta de estilo y funcionalidad. Su estructura modular permite configuraciones personalizables, adaptándose a diferentes estilos de decoración y necesidades de espacio.', img: producto67, categoria: 'estudio' },
    { id: 68, nombre: 'Biblioteca Baja Osaka modular',                      descripcion: 'La Biblioteca Baja Osaka modular es una solución elegante y funcional para el almacenamiento y la exhibición de libros y decoraciones. Su diseño contemporáneo y bajo permite aprovechar el espacio sin ocupar demasiado verticalmente, lo que la hace ideal para salas de estar, oficinas o espacios de trabajo. Equipado con estantes ajustables y compartimentos, esta biblioteca ofrece flexibilidad para organizar objetos de diferentes tamaños, desde libros hasta decoraciones. Fabricada con materiales de alta calidad, la Biblioteca Osaka garantiza durabilidad y resistencia, mientras que sus acabados modernos añaden un toque de estilo a cualquier ambiente. Su estructura modular permite adaptarla fácilmente a distintas configuraciones, convirtiéndola en una opción versátil para cualquier hogar.', img: producto68, categoria: 'estudio' },
    { id: 69, nombre: 'Escritorio Sake modular pequeño',                    descripcion: 'El Escritorio Sake modular pequeño es una solución compacta y funcional, ideal para espacios reducidos. Su diseño minimalista maximiza la superficie de trabajo, proporcionando suficiente espacio para computadoras, documentos y útiles de oficina sin ocupar mucho lugar. Este escritorio cuenta con estantes y compartimentos que facilitan la organización, manteniendo el área de trabajo despejada y ordenada. Fabricado con materiales de alta calidad, el Sake es resistente y duradero, lo que garantiza su uso a largo plazo. Su estilo moderno se adapta a diferentes decoraciones, convirtiéndolo en la opción perfecta para oficinas en casa, dormitorios o cualquier rincón que necesite un espacio de trabajo eficiente y estético.', img: producto69, categoria: 'estudio' },
    { id: 70, nombre: 'Escritorio Mikasa modular',                          descripcion: 'El Escritorio Mikasa modular es una elección sofisticada y práctica para cualquier espacio de trabajo. Su diseño elegante y contemporáneo proporciona una amplia superficie ideal para estudiar o trabajar, mientras que su estructura modular permite personalizar la configuración según tus necesidades específicas. Equipado con compartimentos y estantes, el Mikasa facilita la organización de documentos, dispositivos y materiales, ayudando a mantener el área despejada y funcional. Fabricado con materiales de alta calidad, este escritorio garantiza durabilidad y resistencia, mientras que su acabado moderno añade un toque estético a tu oficina o estudio. Su versatilidad y estilo lo convierten en la opción perfecta para quienes buscan un ambiente de trabajo cómodo y atractivo.', img: producto70, categoria: 'estudio' },
    { id: 71, nombre: 'Biblioteca Alta Osaka modular',                      descripcion: 'La Biblioteca Alta Osaka modular es la solución ideal para quienes buscan maximizar el almacenamiento sin sacrificar el estilo. Su diseño vertical aprovecha al máximo el espacio disponible, proporcionando estantes amplios y ajustables que permiten organizar libros, decoraciones y otros objetos personales. Perfecta para salas de estar, oficinas o estudios, esta biblioteca combina funcionalidad y elegancia, adaptándose a diferentes estilos de decoración. Fabricada con materiales de alta calidad, la Biblioteca Osaka garantiza durabilidad y resistencia, asegurando un uso prolongado. Su estructura modular permite configuraciones personalizables, lo que la convierte en una opción versátil y práctica para cualquier hogar.', img: producto71, categoria: 'estudio' },
    { id: 72, nombre: 'Escritorio en L Aisha Wengue modular',               descripcion: 'El Escritorio en L Aisha modular es una opción elegante y versátil diseñada para optimizar el espacio de trabajo en cualquier entorno. Su estructura en forma de L permite maximizar las esquinas, proporcionando una amplia superficie para trabajar y almacenar materiales. Este escritorio cuenta con compartimentos integrados y estantes ajustables, lo que facilita la organización de documentos, dispositivos y accesorios, manteniendo todo al alcance y en orden. Fabricado con materiales de alta calidad y acabados modernos, el Aisha no solo es duradero, sino que también añade un toque contemporáneo a tu oficina o estudio. Su diseño modular se adapta fácilmente a diferentes configuraciones, convirtiéndolo en una solución práctica y estilizada para espacios de trabajo dinámicos', img: producto72, categoria: 'estudio' },
];

export const categorias = ['zona gamer', 'habitación', 'sala', 'estudio'];
export const fondoImagen = fondo;
